# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: www.cosmic-current.com
title: Cosmic-Current.com
email: vidstanu@gmail.com
description: > # "Use the cosmic powers to enlighten and lift yourself with your guide : Vidushi"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/
  - title: github
    url: https://github.com/
  - title: linkedin
    url:
